export const quiz = {
    totalQuestions: 100,
    questions: [
        {
            id: 1,
            question: "What is the capital of France?",
            answers: ["Madrid", "Paris", "Rome", "Berlin"],
            correctAnswer: "Paris",
        },
        {
            id: 2,
            question: "What is the largest planet in our solar system?",
            answers: ["Mars", "Jupiter", "Venus", "Saturn"],
            correctAnswer: "Jupiter",
        },
        {
            id: 3,
            question: "What is the smallest country in the world?",
            answers: ["Monaco", "Maldives", "Vatican City", "San Marino"],
            correctAnswer: "Vatican City",
        },
        {
            id: 4,
            question: "What is the most widely spoken language in the world?",
            answers: ["English", "Mandarin", "Spanish", "Hindi"],
            correctAnswer: "Mandarin",
        },
        {
            id: 5,
            question: "Who is the founder of Microsoft?",
            answers: [
                "Steve Jobs",
                "Bill Gates",
                "Elon Musk",
                "Mark Zuckerberg",
            ],
            correctAnswer: "Bill Gates",
        },
        {
            id: 6,
            question: "Who painted the Mona Lisa?",
            answers: [
                "Leonardo da Vinci",
                "Vincent van Gogh",
                "Pablo Picasso",
                "Michelangelo",
            ],
            correctAnswer: "Leonardo da Vinci",
        },
        {
            id: 7,
            question: "What is the chemical symbol for gold?",
            answers: ["Go", "Ag", "Au", "Gi"],
            correctAnswer: "Au",
        },
        {
            id: 8,
            question: "Which country is known as the 'Land of the Rising Sun'?",
            answers: ["China", "Japan", "Korea", "Thailand"],
            correctAnswer: "Japan",
        },
        {
            id: 9,
            question: "Who wrote the play 'Romeo and Juliet'?",
            answers: [
                "William Shakespeare",
                "Jane Austen",
                "Charles Dickens",
                "Emily Bronte",
            ],
            correctAnswer: "William Shakespeare",
        },
        {
            id: 10,
            question: "What is the tallest mountain in the world?",
            answers: [
                "Mount Kilimanjaro",
                "Mount Everest",
                "Mount Fuji",
                "Mount McKinley",
            ],
            correctAnswer: "Mount Everest",
        },
        {
            id: 11,
            question: "What is the largest ocean on Earth?",
            answers: [
                "Atlantic Ocean",
                "Indian Ocean",
                "Arctic Ocean",
                "Pacific Ocean",
            ],
            correctAnswer: "Pacific Ocean",
        },
        {
            id: 12,
            question: "Who was the first person to step on the moon?",
            answers: [
                "Neil Armstrong",
                "Buzz Aldrin",
                "Yuri Gagarin",
                "Alan Shepard",
            ],
            correctAnswer: "Neil Armstrong",
        },
        {
            id: 13,
            question: "What is the capital of Australia?",
            answers: ["Melbourne", "Canberra", "Sydney", "Brisbane"],
            correctAnswer: "Canberra",
        },
        {
            id: 14,
            question: "Which planet is known as the 'Red Planet'?",
            answers: ["Mars", "Mercury", "Jupiter", "Saturn"],
            correctAnswer: "Mars",
        },
        {
            id: 15,
            question: "Who painted the ceiling of the Sistine Chapel?",
            answers: [
                "Leonardo da Vinci",
                "Pablo Picasso",
                "Michelangelo",
                "Vincent van Gogh",
            ],
            correctAnswer: "Michelangelo",
        },
        {
            id: 16,
            question:
                "Which scientist formulated the theory of general relativity?",
            answers: [
                "Isaac Newton",
                "Albert Einstein",
                "Stephen Hawking",
                "Nikola Tesla",
            ],
            correctAnswer: "Albert Einstein",
        },
        {
            id: 17,
            question: "Which country is home to the Great Barrier Reef?",
            answers: ["Australia", "Brazil", "India", "Mexico"],
            correctAnswer: "Australia",
        },
        {
            id: 18,
            question: "Who is the author of the 'Harry Potter' book series?",
            answers: [
                "J.K. Rowling",
                "Stephen King",
                "George R.R. Martin",
                "Suzanne Collins",
            ],
            correctAnswer: "J.K. Rowling",
        },
        {
            id: 19,
            question:
                "Which war was fought between the North and the South of the United States?",
            answers: [
                "World War I",
                "Vietnam War",
                "American Civil War",
                "World War II",
            ],
            correctAnswer: "American Civil War",
        },
        {
            id: 20,
            question: "What is the largest continent?",
            answers: ["Asia", "Europe", "Africa", "North America"],
            correctAnswer: "Asia",
        },
        {
            id: 21,
            question: "Who is the Greek god of thunder?",
            answers: ["Poseidon", "Apollo", "Zeus", "Hades"],
            correctAnswer: "Zeus",
        },
        {
            id: 22,
            question: "What is the chemical symbol for iron?",
            answers: ["Fe", "Ir", "In", "I"],
            correctAnswer: "Fe",
        },
        {
            id: 23,
            question: "Which country is famous for its tulip fields?",
            answers: ["Italy", "France", "Netherlands", "Germany"],
            correctAnswer: "Netherlands",
        },
        {
            id: 24,
            question: "Who painted the famous artwork 'The Starry Night'?",
            answers: [
                "Vincent van Gogh",
                "Leonardo da Vinci",
                "Pablo Picasso",
                "Michelangelo",
            ],
            correctAnswer: "Vincent van Gogh",
        },
        {
            id: 25,
            question: "Which country is known as the 'Land Down Under'?",
            answers: ["New Zealand", "Canada", "Australia", "South Africa"],
            correctAnswer: "Australia",
        },
        {
            id: 26,
            question: "Which element has the chemical symbol 'H'?",
            answers: ["Hydrogen", "Helium", "Hassium", "Hafnium"],
            correctAnswer: "Hydrogen",
        },
        {
            id: 27,
            question: "In which city is the Eiffel Tower located?",
            answers: ["Rome", "London", "Paris", "Athens"],
            correctAnswer: "Paris",
        },
        {
            id: 28,
            question: "Which planet is known as the 'Blue Planet'?",
            answers: ["Mars", "Jupiter", "Venus", "Earth"],
            correctAnswer: "Earth",
        },
        {
            id: 29,
            question: "Who is the author of 'To Kill a Mockingbird'?",
            answers: [
                "Harper Lee",
                "F. Scott Fitzgerald",
                "Ernest Hemingway",
                "J.D. Salinger",
            ],
            correctAnswer: "Harper Lee",
        },
        {
            id: 30,
            question: "What is the capital of Germany?",
            answers: ["Berlin", "Munich", "Hamburg", "Frankfurt"],
            correctAnswer: "Berlin",
        },
        {
            id: 31,
            question: "Which planet is known for its beautiful rings?",
            answers: ["Mars", "Saturn", "Neptune", "Uranus"],
            correctAnswer: "Saturn",
        },
        {
            id: 32,
            question: "Who was the first President of the United States?",
            answers: [
                "George Washington",
                "Abraham Lincoln",
                "Thomas Jefferson",
                "John F. Kennedy",
            ],
            correctAnswer: "George Washington",
        },
        {
            id: 33,
            question: "What is the largest species of shark?",
            answers: [
                "Great White Shark",
                "Hammerhead Shark",
                "Whale Shark",
                "Tiger Shark",
            ],
            correctAnswer: "Whale Shark",
        },
        {
            id: 34,
            question:
                "Which country is known for the ancient ruins of Machu Picchu?",
            answers: ["Brazil", "Argentina", "Peru", "Chile"],
            correctAnswer: "Peru",
        },
        {
            id: 35,
            question: "Who is the author of the 'Lord of the Rings' trilogy?",
            answers: [
                "J.R.R. Tolkien",
                "C.S. Lewis",
                "George R.R. Martin",
                "J.K. Rowling",
            ],
            correctAnswer: "J.R.R. Tolkien",
        },
        {
            id: 36,
            question:
                "Which war was fought between the United States and Vietnam?",
            answers: ["World War I", "Korean War", "Vietnam War", "Cold War"],
            correctAnswer: "Vietnam War",
        },
        {
            id: 37,
            question: "What is the largest desert in the world?",
            answers: [
                "Sahara Desert",
                "Gobi Desert",
                "Atacama Desert",
                "Antarctic Desert",
            ],
            correctAnswer: "Sahara Desert",
        },
        {
            id: 38,
            question: "Who is the author of the novel 'Pride and Prejudice'?",
            answers: [
                "Jane Austen",
                "Charlotte Bronte",
                "Emily Bronte",
                "Louisa May Alcott",
            ],
            correctAnswer: "Jane Austen",
        },
        {
            id: 39,
            question: "What is the capital of Brazil?",
            answers: ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador"],
            correctAnswer: "Brasilia",
        },
        {
            id: 40,
            question: "Which country is known for the pyramids?",
            answers: ["Egypt", "Greece", "Italy", "Mexico"],
            correctAnswer: "Egypt",
        },
        {
            id: 41,
            question: "Who is the author of the novel '1984'?",
            answers: [
                "George Orwell",
                "Aldous Huxley",
                "Ray Bradbury",
                "Margaret Atwood",
            ],
            correctAnswer: "George Orwell",
        },
        {
            id: 42,
            question: "What is the largest lake in Africa?",
            answers: [
                "Lake Victoria",
                "Lake Tanganyika",
                "Lake Malawi",
                "Lake Chad",
            ],
            correctAnswer: "Lake Victoria",
        },
        {
            id: 43,
            question: "Who is the author of the play 'Hamlet'?",
            answers: [
                "William Shakespeare",
                "Samuel Beckett",
                "Oscar Wilde",
                "Anton Chekhov",
            ],
            correctAnswer: "William Shakespeare",
        },
        {
            id: 44,
            question: "Which country is known for the Great Wall?",
            answers: ["China", "Japan", "India", "Russia"],
            correctAnswer: "China",
        },
        {
            id: 45,
            question: "What is the chemical symbol for silver?",
            answers: ["Si", "Ag", "Au", "Sr"],
            correctAnswer: "Ag",
        },
        {
            id: 46,
            question: "Which city hosted the 2016 Summer Olympics?",
            answers: ["London", "Rio de Janeiro", "Beijing", "Tokyo"],
            correctAnswer: "Rio de Janeiro",
        },
        {
            id: 47,
            question: "Who wrote the novel 'The Catcher in the Rye'?",
            answers: [
                "J.D. Salinger",
                "F. Scott Fitzgerald",
                "Ernest Hemingway",
                "Harper Lee",
            ],
            correctAnswer: "J.D. Salinger",
        },
        {
            id: 48,
            question: "What is the capital of India?",
            answers: ["Mumbai", "Delhi", "Kolkata", "Chennai"],
            correctAnswer: "Delhi",
        },
        {
            id: 49,
            question: "Which planet is known as the 'Giant Planet'?",
            answers: ["Mars", "Jupiter", "Venus", "Uranus"],
            correctAnswer: "Jupiter",
        },
        {
            id: 50,
            question: "Who is the author of the play 'Macbeth'?",
            answers: [
                "William Shakespeare",
                "Arthur Miller",
                "Tennessee Williams",
                "Samuel Beckett",
            ],
            correctAnswer: "William Shakespeare",
        },
        {
            id: 51,
            question: "What is the largest river in the world?",
            answers: [
                "Nile River",
                "Amazon River",
                "Yangtze River",
                "Mississippi River",
            ],
            correctAnswer: "Amazon River",
        },
        {
            id: 52,
            question: "Who is the Greek god of the sea?",
            answers: ["Poseidon", "Apollo", "Zeus", "Hades"],
            correctAnswer: "Poseidon",
        },
        {
            id: 53,
            question: "What is the chemical symbol for oxygen?",
            answers: ["O", "Og", "Om", "Op"],
            correctAnswer: "O",
        },
        {
            id: 54,
            question: "Which country is known as the 'Land of Fire and Ice'?",
            answers: ["Iceland", "Norway", "Finland", "Greenland"],
            correctAnswer: "Iceland",
        },
        {
            id: 55,
            question: "Who painted the Mona Lisa?",
            answers: [
                "Leonardo da Vinci",
                "Pablo Picasso",
                "Michelangelo",
                "Vincent van Gogh",
            ],
            correctAnswer: "Leonardo da Vinci",
        },
        {
            id: 56,
            question: "Which scientist is known for his theory of evolution?",
            answers: [
                "Isaac Newton",
                "Albert Einstein",
                "Charles Darwin",
                "Nikola Tesla",
            ],
            correctAnswer: "Charles Darwin",
        },
        {
            id: 57,
            question: "Which country is known for the Taj Mahal?",
            answers: ["India", "China", "Japan", "Thailand"],
            correctAnswer: "India",
        },
        {
            id: 58,
            question: "Who is the author of the novel 'The Great Gatsby'?",
            answers: [
                "F. Scott Fitzgerald",
                "Ernest Hemingway",
                "Harper Lee",
                "J.D. Salinger",
            ],
            correctAnswer: "F. Scott Fitzgerald",
        },
        {
            id: 59,
            question:
                "Which war was fought between the United States and Great Britain?",
            answers: [
                "World War I",
                "American Revolutionary War",
                "World War II",
                "Cold War",
            ],
            correctAnswer: "American Revolutionary War",
        },
        {
            id: 60,
            question: "What is the largest ocean in the world?",
            answers: [
                "Atlantic Ocean",
                "Indian Ocean",
                "Arctic Ocean",
                "Pacific Ocean",
            ],
            correctAnswer: "Pacific Ocean",
        },
        {
            id: 61,
            question: "Who is the Greek goddess of love and beauty?",
            answers: ["Aphrodite", "Hera", "Artemis", "Athena"],
            correctAnswer: "Aphrodite",
        },
        {
            id: 62,
            question: "What is the chemical symbol for gold?",
            answers: ["Go", "Ag", "Au", "Gi"],
            correctAnswer: "Au",
        },
        {
            id: 63,
            question: "Which country is known for the fjords?",
            answers: ["Sweden", "Norway", "Denmark", "Finland"],
            correctAnswer: "Norway",
        },
        {
            id: 64,
            question: "Who painted the famous artwork 'The Last Supper'?",
            answers: [
                "Leonardo da Vinci",
                "Vincent van Gogh",
                "Pablo Picasso",
                "Michelangelo",
            ],
            correctAnswer: "Leonardo da Vinci",
        },
        {
            id: 65,
            question: "Which country is known as the 'Rainbow Nation'?",
            answers: ["Canada", "Australia", "South Africa", "New Zealand"],
            correctAnswer: "South Africa",
        },
        {
            id: 66,
            question: "Which element has the chemical symbol 'C'?",
            answers: ["Carbon", "Calcium", "Copper", "Chlorine"],
            correctAnswer: "Carbon",
        },
        {
            id: 67,
            question: "In which city is the Statue of Liberty located?",
            answers: ["New York City", "Los Angeles", "Chicago", "Boston"],
            correctAnswer: "New York City",
        },
        {
            id: 68,
            question: "Who wrote the novel 'Moby-Dick'?",
            answers: [
                "Herman Melville",
                "Mark Twain",
                "Nathaniel Hawthorne",
                "Ralph Waldo Emerson",
            ],
            correctAnswer: "Herman Melville",
        },
        {
            id: 69,
            question:
                "Which country is known for the Angkor Wat temple complex?",
            answers: ["Thailand", "Cambodia", "Vietnam", "Laos"],
            correctAnswer: "Cambodia",
        },
        {
            id: 70,
            question: "Who is the author of the novel 'The Hobbit'?",
            answers: [
                "J.R.R. Tolkien",
                "C.S. Lewis",
                "George R.R. Martin",
                "J.K. Rowling",
            ],
            correctAnswer: "J.R.R. Tolkien",
        },
        {
            id: 71,
            question: "What is the largest continent in the world?",
            answers: ["North America", "Europe", "Africa", "Asia"],
            correctAnswer: "Asia",
        },
        {
            id: 72,
            question: "Who is the Norse god of thunder?",
            answers: ["Thor", "Loki", "Odin", "Freyja"],
            correctAnswer: "Thor",
        },
        {
            id: 73,
            question: "What is the chemical symbol for iron?",
            answers: ["Fe", "I", "Ir", "In"],
            correctAnswer: "Fe",
        },
        {
            id: 74,
            question: "Which country is known for the Galapagos Islands?",
            answers: ["Ecuador", "Mexico", "Colombia", "Brazil"],
            correctAnswer: "Ecuador",
        },
        {
            id: 75,
            question: "Who painted the artwork 'Starry Night'?",
            answers: [
                "Vincent van Gogh",
                "Pablo Picasso",
                "Leonardo da Vinci",
                "Salvador Dali",
            ],
            correctAnswer: "Vincent van Gogh",
        },
        {
            id: 76,
            question: "Which scientist is known for his theory of relativity?",
            answers: [
                "Isaac Newton",
                "Albert Einstein",
                "Charles Darwin",
                "Nikola Tesla",
            ],
            correctAnswer: "Albert Einstein",
        },
        {
            id: 77,
            question: "Which country is known for the Stonehenge monument?",
            answers: ["England", "Scotland", "Ireland", "Wales"],
            correctAnswer: "England",
        },
        {
            id: 78,
            question: "Who is the author of the novel 'The Odyssey'?",
            answers: ["Homer", "Virgil", "Ovid", "Sophocles"],
            correctAnswer: "Homer",
        },
        {
            id: 79,
            question:
                "Which war was fought between the United States and Iraq?",
            answers: ["World War I", "Korean War", "Gulf War", "Cold War"],
            correctAnswer: "Gulf War",
        },
        {
            id: 80,
            question: "What is the largest coral reef system in the world?",
            answers: [
                "Great Barrier Reef",
                "Belize Barrier Reef",
                "Red Sea Coral Reef",
                "Mesoamerican Barrier Reef",
            ],
            correctAnswer: "Great Barrier Reef",
        },
        {
            id: 81,
            question: "Who is the Roman god of war?",
            answers: ["Mars", "Jupiter", "Apollo", "Mercury"],
            correctAnswer: "Mars",
        },
        {
            id: 82,
            question: "What is the chemical symbol for calcium?",
            answers: ["Ca", "Cl", "Cu", "C"],
            correctAnswer: "Ca",
        },
        {
            id: 83,
            question: "Which country is known for the Acropolis?",
            answers: ["Greece", "Italy", "Turkey", "Egypt"],
            correctAnswer: "Greece",
        },
        {
            id: 84,
            question: "Who wrote the play 'Romeo and Juliet'?",
            answers: [
                "William Shakespeare",
                "Samuel Beckett",
                "Oscar Wilde",
                "Anton Chekhov",
            ],
            correctAnswer: "William Shakespeare",
        },
        {
            id: 85,
            question: "What is the capital of Australia?",
            answers: ["Sydney", "Melbourne", "Brisbane", "Canberra"],
            correctAnswer: "Canberra",
        },
        {
            id: 86,
            question: "Which planet is known as the 'Red Planet'?",
            answers: ["Mars", "Jupiter", "Venus", "Mercury"],
            correctAnswer: "Mars",
        },
        {
            id: 87,
            question: "Who is the author of the novel 'To Kill a Mockingbird'?",
            answers: [
                "Harper Lee",
                "F. Scott Fitzgerald",
                "Ernest Hemingway",
                "J.D. Salinger",
            ],
            correctAnswer: "Harper Lee",
        },
        {
            id: 88,
            question: "What is the capital of Canada?",
            answers: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
            correctAnswer: "Ottawa",
        },
        {
            id: 89,
            question: "Which planet is known as the 'Ringed Planet'?",
            answers: ["Mars", "Jupiter", "Saturn", "Uranus"],
            correctAnswer: "Saturn",
        },
        {
            id: 90,
            question: "Who is the author of the play 'Romeo and Juliet'?",
            answers: [
                "William Shakespeare",
                "Arthur Miller",
                "Tennessee Williams",
                "Samuel Beckett",
            ],
            correctAnswer: "William Shakespeare",
        },
        {
            id: 91,
            question: "What is the longest river in South America?",
            answers: [
                "Amazon River",
                "Mississippi River",
                "Nile River",
                "Yangtze River",
            ],
            correctAnswer: "Amazon River",
        },
        {
            id: 92,
            question: "Who is the Greek god of the underworld?",
            answers: ["Hades", "Apollo", "Zeus", "Poseidon"],
            correctAnswer: "Hades",
        },
        {
            id: 93,
            question: "What is the chemical symbol for helium?",
            answers: ["H", "He", "Hi", "Hu"],
            correctAnswer: "He",
        },
        {
            id: 94,
            question: "Which country is known as the 'Land Down Under'?",
            answers: ["United States", "Canada", "Australia", "New Zealand"],
            correctAnswer: "Australia",
        },
        {
            id: 95,
            question: "Who painted the artwork 'The Starry Night'?",
            answers: [
                "Vincent van Gogh",
                "Pablo Picasso",
                "Leonardo da Vinci",
                "Salvador Dali",
            ],
            correctAnswer: "Vincent van Gogh",
        },
        {
            id: 96,
            question: "Which scientist is known for his theory of gravity?",
            answers: [
                "Isaac Newton",
                "Albert Einstein",
                "Charles Darwin",
                "Nikola Tesla",
            ],
            correctAnswer: "Isaac Newton",
        },
        {
            id: 97,
            question: "Which country is known for the Colosseum?",
            answers: ["Italy", "Greece", "France", "Spain"],
            correctAnswer: "Italy",
        },
        {
            id: 98,
            question: "Who is the author of the novel 'Pride and Prejudice'?",
            answers: [
                "Jane Austen",
                "Emily Bronte",
                "Charlotte Bronte",
                "Louisa May Alcott",
            ],
            correctAnswer: "Jane Austen",
        },
        {
            id: 99,
            question:
                "Which war was fought between the United States and Japan?",
            answers: [
                "World War I",
                "American Civil War",
                "World War II",
                "Vietnam War",
            ],
            correctAnswer: "World War II",
        },
        {
            id: 100,
            question: "What is the largest desert in the world?",
            answers: [
                "Sahara Desert",
                "Gobi Desert",
                "Atacama Desert",
                "Antarctic Desert",
            ],
            correctAnswer: "Sahara Desert",
        },
    ],
};
